#!/bin/bash

module load anaconda3/5.3.0
module load web_proxy/1.0
conda create -n ncbiDL -c bioconda ncbi-genome-download
source activate ncbiDL
ncbi-genome-download --genera "Staphylococcus argenteus" bacteria
